Codveda Technologies Internship

In [32]:
import pandas as pd
import numpy as np

load dataset

In [33]:
Sentiment_data = pd.read_csv(r"c:\Users\User\Documents\Sentiment_dataset.csv")

In [34]:
Sentiment_data.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,15/01/2023 12:30,User123,Twitter,#Nature #Park,15,30,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,15/01/2023 8:45,CommuterX,Twitter,#Traffic #Morning,5,10,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,15/01/2023 15:45,FitnessFan,Instagram,#Fitness #Workout,20,40,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,15/01/2023 18:20,AdventureX,Facebook,#Travel #Adventure,8,15,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,15/01/2023 19:55,ChefCook,Instagram,#Cooking #Food,12,25,Australia,2023,1,15,19

data information

In [35]:
Sentiment_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    object
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    int64
 9   Likes         732 non-null    int64
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: int64(8), object(7)
memory usage: 85.9+ KB

checking for missing value

In [36]:
Sentiment_data.isnull().sum()

Unnamed: 0.1    0
Unnamed: 0      0
Text            0
Sentiment       0
Timestamp       0
User            0
Platform        0
Hashtags        0
Retweets        0
Likes           0
Country         0
Year            0
Month           0
Day             0
Hour            0
dtype: int64

removing duplicate if any

In [37]:
Sentiment_data.duplicated().sum()

np.int64(0)

from our datasets we have unecessary column

In [38]:
Sentiment_data = Sentiment_data.drop(columns=["Unnamed: 0.1", "Unnamed: 0"])
Sentiment_data.head()

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,Enjoying a beautiful day at the park! ...,Positive,15/01/2023 12:30,User123,Twitter,#Nature #Park,15,30,USA,2023,1,15,12
1,Traffic was terrible this morning. ...,Negative,15/01/2023 8:45,CommuterX,Twitter,#Traffic #Morning,5,10,Canada,2023,1,15,8
2,Just finished an amazing workout! 💪 ...,Positive,15/01/2023 15:45,FitnessFan,Instagram,#Fitness #Workout,20,40,USA,2023,1,15,15
3,Excited about the upcoming weekend getaway! ...,Positive,15/01/2023 18:20,AdventureX,Facebook,#Travel #Adventure,8,15,UK,2023,1,15,18
4,Trying out a new recipe for dinner tonight. ...,Neutral,15/01/2023 19:55,ChefCook,Instagram,#Cooking #Food,12,25,Australia,2023,1,15,19

then we need to fix the timestamp column

In [39]:
Sentiment_data["Timestamp"] = pd.to_datetime(Sentiment_data["Timestamp"])

C:\Users\User\AppData\Local\Temp\ipykernel_8848\3475009440.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  Sentiment_data["Timestamp"] = pd.to_datetime(Sentiment_data["Timestamp"])

we fit to date and time columns

In [40]:
Sentiment_data["Date"] = Sentiment_data["Timestamp"].dt.date
Sentiment_data.head()

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,Date
0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15,30,USA,2023,1,15,12,2023-01-15
1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5,10,Canada,2023,1,15,8,2023-01-15
2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20,40,USA,2023,1,15,15,2023-01-15
3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8,15,UK,2023,1,15,18,2023-01-15
4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12,25,Australia,2023,1,15,19,2023-01-15

In [41]:
Sentiment_data["Time"] = Sentiment_data["Timestamp"].dt.time
Sentiment_data.head()

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,Date,Time
0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15,30,USA,2023,1,15,12,2023-01-15,12:30:00
1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5,10,Canada,2023,1,15,8,2023-01-15,08:45:00
2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20,40,USA,2023,1,15,15,2023-01-15,15:45:00
3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8,15,UK,2023,1,15,18,2023-01-15,18:20:00
4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12,25,Australia,2023,1,15,19,2023-01-15,19:55:00

then we delect the timestamp column

In [42]:
Sentiment_data = Sentiment_data.drop(columns=["Timestamp"])
Sentiment_data.head()

,Text,Sentiment,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,Date,Time
0,Enjoying a beautiful day at the park! ...,Positive,User123,Twitter,#Nature #Park,15,30,USA,2023,1,15,12,2023-01-15,12:30:00
1,Traffic was terrible this morning. ...,Negative,CommuterX,Twitter,#Traffic #Morning,5,10,Canada,2023,1,15,8,2023-01-15,08:45:00
2,Just finished an amazing workout! 💪 ...,Positive,FitnessFan,Instagram,#Fitness #Workout,20,40,USA,2023,1,15,15,2023-01-15,15:45:00
3,Excited about the upcoming weekend getaway! ...,Positive,AdventureX,Facebook,#Travel #Adventure,8,15,UK,2023,1,15,18,2023-01-15,18:20:00
4,Trying out a new recipe for dinner tonight. ...,Neutral,ChefCook,Instagram,#Cooking #Food,12,25,Australia,2023,1,15,19,2023-01-15,19:55:00

In [43]:
Sentiment_data.dtypes

Text         object
Sentiment    object
User         object
Platform     object
Hashtags     object
Retweets      int64
Likes         int64
Country      object
Year          int64
Month         int64
Day           int64
Hour          int64
Date         object
Time         object
dtype: object

then our data is cleaned we save the cleaned data

In [44]:
Sentiment_data.to_csv("Cleaned_Sentiment_data.csv", index=False)

In [45]:
Sentiment_data.head(732)

,Text,Sentiment,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,Date,Time
0,Enjoying a beautiful day at the park! ...,Positive,User123,Twitter,#Nature #Park,15,30,USA,2023,1,15,12,2023-01-15,12:30:00
1,Traffic was terrible this morning. ...,Negative,CommuterX,Twitter,#Traffic #Morning,5,10,Canada,2023,1,15,8,2023-01-15,08:45:00
2,Just finished an amazing workout! 💪 ...,Positive,FitnessFan,Instagram,#Fitness #Workout,20,40,USA,2023,1,15,15,2023-01-15,15:45:00
3,Excited about the upcoming weekend getaway! ...,Positive,AdventureX,Facebook,#Travel #Adventure,8,15,UK,2023,1,15,18,2023-01-15,18:20:00
4,Trying out a new recipe for dinner tonight. ...,Neutral,ChefCook,Instagram,#Cooking #Food,12,25,Australia,2023,1,15,19,2023-01-15,19:55:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,Collaborating on a science project that receiv...,Happy,ScienceProjectSuccessHighSchool,Facebook,#ScienceFairWinner #HighSchoolScience,20,39,UK,2017,8,18,18,2017-08-18,18:20:00
728,Attending a surprise birthday party organized ...,Happy,BirthdayPartyJoyHighSchool,Instagram,#SurpriseCelebration #HighSchoolFriendship,25,48,USA,2018,6,22,14,2018-06-22,14:15:00
729,Successfully fundraising for a school charity ...,Happy,CharityFundraisingTriumphHighSchool,Twitter,#CommunityGiving #HighSchoolPhilanthropy,22,42,Canada,2019,4,5,17,2019-04-05,17:30:00
730,"Participating in a multicultural festival, cel...",Happy,MulticulturalFestivalJoyHighSchool,Facebook,#CulturalCelebration #HighSchoolUnity,21,43,UK,2020,2,29,20,2020-02-29,20:45:00
731,Organizing a virtual talent show during challe...,Happy,VirtualTalentShowSuccessHighSchool,Instagram,#VirtualEntertainment #HighSchoolPositivity,24,47,USA,2020,11,15,15,2020-11-15,15:15:00

In [ ]:
thank you